global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'core-platform-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['core-platform-service:8080']

  - job_name: 'ingestion-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingestion-service:8081']
